spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      master-data-source:
        url: jdbc:mysql://127.0.0.1:3306/dp-boot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: test
      # slave-data-source:
      #   url: jdbc:mysql://127.0.0.1:3306/dp-boot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      #   username: root
      #   password: test
        initial-size: 10
        max-active: 100
        min-idle: 10
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 300000
        min-evictable-idle-time-millis: 1800000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          #login-username: admin
          #login-password: admin
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true
  redis:
#  ip
    host: 192.168.0.164
#    端口
    port: 6379
#    密码
    password: zaq123ZMT
    #默认是索引为0的数据库
    database: 0
#    超时
    timeout: 10000
    jedis:
      pool:
#      最大活跃量
        max-active: 6000
#        最大等待时间
        max-wait: 1000
#        最小空闲量
        max-idle: 400


logging:
  file: log/dp-boot.log